Develop
genga911/yandex-praktikum-graduation-project pull request #1
Opened 2022-04-24 08:12 UTC by genga911

2022-05-02 08:13 UTC, ASPecherkin requested changes
Оставил комментарии, в остальном всё нормально

2022-05-02 08:13 UTC, ASPecherkin commented on app/database/db.go
> +		panic(fmt.Sprintf("DB ping error: %s", err))
можно и так делать, 
но обычно принято пробрасыввать ошибку наверх в main и в нём уже паниковать

2022-05-02 08:13 UTC, ASPecherkin commented on app/database/db.go
> +	db.createTables()
получается , что таблицы будут дропаться при каждом запуске приложения? 

Кажется, что такого быть не должно

2022-05-02 08:13 UTC, ASPecherkin commented on app/database/repository/order.go
> +	orders, err := or.List(u, false)
лучше тут добавить параметр, который будет ограничивать количетсво заказов для sync
Чтобы не получить слишком много

2022-05-02 15:38 UTC, genga911 commented on app/database/db.go
> +	db.createTables()
Так сделано специально, иначе не пройдут тесты в гитхабе, так как при их запуске БД не обновляется, эту проблему обсуждали в слаке еще при выполнении инкрементов прошлых работ, там было применено такое же решение.

2022-05-02 15:40 UTC, genga911 commented on app/database/repository/order.go
> +	orders, err := or.List(u, false)
в задании четко написано:"Общее количество запросов информации о начислении не ограничено." 
в пункте взаимодействия с внешней системой, если я буду вводить ограничения, есть возможность не вписаться в тайминги тестов

2022-05-03 09:35 UTC, genga911 commented on app/database/db.go
> +		panic(fmt.Sprintf("DB ping error: %s", err))
пробросил ошибку до самого верха, исправлено

2022-05-03 09:36 UTC, genga911 commented on app/database/db.go
> +	db.createTables()
Убрал удаление таблиц при старте приложения, вроде тесты прошли нормально, но повторюсь такая проблема была в прошлых инкрементах, и решение было взято из прошлой работы

2022-05-03 09:36 UTC, genga911 commented on app/database/repository/order.go
> +	orders, err := or.List(u, false)
разделил запросы на группы по 10 штук

2022-05-05 12:16 UTC, ASPecherkin approved these changes
принимаю работу

2022-05-06 13:55 UTC, merged